### ISSUE TITLE
Question: Flag: Respawn-location

### ISSUE THREAD

**Issue by donvdp** [aromaa/WorldGuardExtraFlagsPlugin#147]
Hi, im seeing an extra flag called "respawn-location". as described in the 'overview' page, this should let the players respawn at a certain location. However this does not seem to work. whenever my player dies they get respawned to there essentials respawn home (bed). Is there any way to let worldguard extra flag to take over this respawn location when a players is inside the region?

![image](https://user-images.githubusercontent.com/10013800/100452331-361ec000-30b9-11eb-9846-7cbb7bd60016.png)

![image](https://user-images.githubusercontent.com/10013800/100452286-1e473c00-30b9-11eb-818b-ef2f18b8bd47.png)

**Comment by aromaa** [comment]
This is already covered in the FAQ.

**Comment by donvdp** [comment]
ive already followed that ... still doesnt work
![image](https://user-images.githubusercontent.com/10013800/100453571-73844d00-30bb-11eb-9267-8bd8159a1986.png)

**Comment by aromaa** [comment]
Then you are bypassing the flag.

And next time, don't open a new issue regarding the same question, thank you.

**Comment by donvdp** [comment]
Im not bypassing the flag as far as i can tell. Ive checked the permissions. but no bypass was found.

and next time, please dont close a ticket without checking if it was resolved because the problem still excists.

**Comment by aromaa** [comment]
I'm assuming that you have restarted your server after changing that? And you are running the latest version of Spgiot?

And I closed the ticket because it sounded like you were having a common problem that's already covered in the FAQ and instead of reading you just posted the issue, like many others.

But even if I close the ticket that doesn't mean you need to spam my Github with issues, thats just quick way of getting blocked from the repo.

**Comment by donvdp** [comment]
Yes, your assuming and thats the issue, communicating with you is a strugle at best, this is the 4th time that ive encountered this issue with you. you can close/delete this ticket, im stopping my attempts to helpy ou improve your plugin.
