### ISSUE TITLE
Unable to build due to outdated dependencies.

### ISSUE THREAD

**Issue by andrewkm** [aromaa/WorldGuardExtraFlagsPlugin#209]
Unable to build due to outdated dependencies.
These dependencies are not located in the repos that are configured.

`[ERROR] Failed to execute goal on project Spigot: Could not resolve dependencies for project net.goldtreeservers.worldguardextraflags:Spigot:jar:4.1.6-SNAPSHOT: Failed to collect dependencies at com.boydti:fawe-api:jar:18.07.27-3ed2e57-1163-20.5.2: Failed to read artifact descriptor for com.boydti:fawe-api:jar:18.07.27-3ed2e57-1163-20.5.2: Could not transfer artifact com.boydti:fawe-api:pom:18.07.27-3ed2e57-1163-20.5.2 from/to empcraft (http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/): Authorization failed for http://ci.athion.net/job/FastAsyncWorldEdit/ws/mvn/com/boydti/fawe-api/18.07.27-3ed2e57-1163-20.5.2/fawe-api-18.07.27-3ed2e57-1163-20.5.2.pom 403 Forbidden -> [Help 1]`

**Comment by aromaa** [comment]
I removed the FAWE support altogether. It has been an unsupported scenario for a while now and all issues related to or due to it has not received any fixes for a while now and the suggested option has been to remove FAWE from the server. WorldEdit has done a lot of performance tweaking since the 1.13+ days and the issues caused by FAWE are greater than whats worthwhile.

**Comment by andrewkm** [comment]
Thank you.
Yes, FAWE is shit lol.
